#!/bin/sh

# path: ~/.config/zsh/

# Aliases
alias ls='ls -F --color=auto'
alias ll='ls -lhF --color=auto'
alias la='ls -lhAF'
alias grep='grep --color=auto'
alias ..='cd ..'
alias c='clear'

alias cdinfai='cd /home/steve/Dokumente/InfAI'
#alias vim='nvim'

alias glola='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --all'
alias push_wiki='git add -A && git commit -a -m "Update Wiki" && git push'

alias git='LANG=en_US.UTF-8 git'

#alias ec="$EDITOR $HOME/.zshrc" # edit .zshrc
#alias sc="source $HOME/.zshrc"  # reload zsh configuration
